### ISSUE TITLE
Build arm64 docker image

### ISSUE THREAD

**Issue by mvelbaum** [openziti/ziti-browzer-bootstrapper#200]
When trying to pull the image on arm64 I get:
```
$ docker pull ghcr.io/openziti/ziti-browzer-bootstrapper:latest
latest: Pulling from openziti/ziti-browzer-bootstrapper
no matching manifest for linux/arm64/v8 in the manifest list entries
```

Would be great if this image was also available, as the rest of the ziti images already support arm.

**Comment by rentallect** [comment]
@mvelbaum I just released v0.39.0 images of the bootstrapper which now include `linux/amd64` and `linux/arm64`.
