### ISSUE TITLE
Allow to run bootstrapper in HTTP while using HTTPS for the bundle URL

### ISSUE THREAD

**Issue by mvelbaum** [openziti/ziti-browzer-bootstrapper#202]
Hi,

I'd like to terminate the TLS on my own and run the bootstrapper in HTTP mode. The problem is when you set `ZITI_BROWZER_BOOTSTRAPPER_SCHEME` and `ZITI_BROWZER_BOOTSTRAPPER_LISTEN_PORT` then the URL it generates for the JS bundle uses those as well.

Is it possible to have something like `EXTERNAL_SCHEME` and `EXTERNAL_PORT`? If unset, then they can use the internal values above.

**Comment by dovholuknf** [comment]
When you say "you" want to terminate TLS on your own, do you just mean you want to use a certificate you provided? The browzer will connect to the bootstrapper to provide the TLS, so technically you are terminating it "on your own"? I'm not quite sure I understand what you're looking to do?

**Comment by rentallect** [comment]
@mvelbaum For clarity, when you say "_terminate the TLS on my own_", do you mean you plan to do something like put the bootstrapper behind a load balancer (LB), then terminate TLS at the LB, and then pass HTTP traffic onto the bootstrapper (which would be listening on HTTP, not HTTPS)?

**Comment by mvelbaum** [comment]
@rentallect exactly. I have HAProxy running as a reverse-proxy which does the TLS termination for multiple services which all listen serve HTTP.

**Comment by rentallect** [comment]
I'll look into the `EXTERNAL_*` concept.  It will be mid to late next week before I can get to it.

**Comment by rentallect** [comment]
@mvelbaum I just released 0.43.0 which contains the support you need to run the Bootstrapper behind HAProxy (or any LB).

Simply add the following new env vars to your config:

`ZITI_BROWZER_LOAD_BALANCER_HOST` is the DNS host name of the LB itself
`ZITI_BROWZER_LOAD_BALANCER_PORT` is the TCP port that the above LB listens on (default is 443)

Let me know how it goes, but in the meantime, I will close this issue.  We can open a new one for any new issues.

Thanks again for using browZer !
