### ISSUE TITLE
No way to re-login on failed authentication

### ISSUE THREAD

**Issue by mvelbaum** [openziti/ziti-browzer-bootstrapper#204]
When you login with credentials that fail authentication on the Ziti network (e.g. an email that does not match an existing identity) then you get a BrowZer runtime error as expected: `User 'foo@bar.com' cannot be authenticated onto Ziti Network`. Unfortunately, there is no way to re-do the login as it seems that the auth token has been cached and you will always be redirected to the failed login page when you try to access the service.

Note: this was tested using Auth0 as the IdP.

**Comment by rentallect** [comment]
I have v0.39.1 in the pipeline.  This build (which has IdP-related updates) should resolve the issue you mentioned here.

**Comment by rentallect** [comment]
`v0.39.1` has been released.  Please give your reported scenario a try under this build.

Following a failed Ziti network auth attempt (as you described), it will be necessary to close the browser tab, wait about a minute (for the browZer Service Worker to terminate), and then a new tab should allow you to retry/succeed with valid Ziti credentials.  Bouncing the browser altogether before retry will also work.

**Comment by mvelbaum** [comment]
The issue is indeed fixed. Thanks!
