### ISSUE TITLE
Add OIDC machine-to-machine authentication support

### ISSUE THREAD

**Issue by rentallect** [openziti/ziti-browzer-bootstrapper#258]
Once the bootstrapper accepts wildcard `vhost` specifications, the bootstrapper’s SNI logic should still only accept `vhost` values matching an existing Ziti Service.  

For example, if an HTTP Request came into the bootstrapper at https://123456.zrok.browzer.cloudziti.io, and the network’s currently-existing set of Services (a.k.a. zrok share tokens) did NOT include 123456, then the bootstrapper should send a 404 Response.

If the network’s existing set of Services (a.k.a. zrok share tokens) DID include 123456, then the bootstrapper should send a 200 Response that includes the traditional HTML salvo that bootstraps the ZBR over in Chrome.

Of course, the bootstrapper cannot know if a given wildcard vhost value matches an existing Ziti Service or not UNLESS it asks the Ziti Controller for the list of existing Services.  Doing this requires the bootstrapper to authenticate onto the Ziti network (something it currently does not do).

So…

If ZITI_BROWZER_BOOTSTRAPPER_ENABLE_ZROK was true, it would activate new OIDC machine-to-machine authentication flows that would allow the bootstrapper to acquire a JWT from an IdP.  Then the bootstrapper would use that JWT to authenticate with the Controller (similar to how the ZBR does it today).  

Once authenticated onto the Ziti network, the bootstrapper would pull the list of Services from the Controller periodically (in ways similar to how the c-sdk does).  

The bootstrapper’s HTTP Request processing, and SNI logic, would then leverage the array of Services acquired from the Controller to make the 404 | 200 determinations.

**Comment by michaelquigley** [comment]
If you do end up using the SDK cache to determine if a service is available or not, you're probably going to have to do the same thing that the public frontend does... when you detect a 404 on a requested share, you're should ask the SDK to refresh that share, and try again... to make sure that it's actually not there, and not just a bad cache state.

**Comment by rentallect** [comment]
Yes, similar to what I do in the (_upcoming_) `zrok nodejs sdk`

**Comment by michaelquigley** [comment]
Yup! Same...

**Comment by rentallect** [comment]
shipped in `0.59.0`
