### ISSUE TITLE
Allow custom tags in the bootstrapper logging

### ISSUE THREAD

**Issue by mguthrie88** [openziti/ziti-browzer-bootstrapper#263]
Would be helpful to be able to pass in some meta variables to the bootstrapper to be able emit as custom fields in the log context. 

Example environment variable:
```
TAGS='{ "myCustomField": "myCustomValue", "myCustomField2": "myCustomValue2"}'
```

Might also be good to put these into their own namespace within the logs so the native log fields can't be clobbered by an environment config. Example: 

```
{
  "url": "/api/v4/users/status/ids",
  "clientIp": "1.1.1.1",
  "method": "POST",
  "timestamp": "2024-05-06T15:23:49.676Z",
  "version": "0.59.1",
  "message": "req terminate; non-GET method",
  "messageType": "DATA_MESSAGE",
  "level": "warn",
  "tags": {
    "myCustomField1": "customValue1",
    "myCustomField2": "customValue2"
  }
}
```

**Comment by rentallect** [comment]
shipped in `0.60.1`
