### ISSUE TITLE
browzer keycloak.min.js optimization

### ISSUE THREAD

**Issue by Apaid** [openziti/ziti-browzer-bootstrapper#336]
I deployed browzer on a computer virtual machine and was able to access the service, but it suddenly became inaccessible yesterday. I checked and found that I could not connect to https://cdn.jsdelivr.net/npm/keycloak-js@23.0.1/dist/keycloak.min.js, and there was no network connection at the time. Can browzer not run in a LAN environment? Can keycloak.min.js be placed locally for access? Suggest optimization it.

Does the jspi token need to be verified by Google when accessing the browzer? Can it be accessed in a LAN environment?

**Comment by rentallect** [comment]
Hi @Apaid 

If your browZer deployment is causing `keycloak.min.js` to be loaded, it means you are running a **_very_** old version of browZer, and you have a bootstrapper config that is specifying `'idp_type: 'keycloak'` (`idp_type` is now obsolete).

What version of browZer are you running?

Yes, the jspi token should function just fine in a LAN env.

**Comment by rentallect** [comment]
@Apaid If you update your browZer release to `0.77.0` (or beyond) you should be fine. I am going to close this issue now. If you re-encounter `keycloak.min.js` issues again, please re-open the issue.
